# -*- coding: utf-8 -*-
"""Assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YNZ9SkTrKsuDVuGfk9Zv9NvEmDVlV51P
"""

x = input("Enter numbers : ").split()
sum = 0
for i in x:
  sum=sum + int(i) 

print(sum)

